services:
  db:
    image: postgres:15-alpine
    container_name: postgres_billing_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_billing_data:/var/lib/postgresql/data
    networks:
      - saas_network
    restart: unless-stopped

  app:
    build: .
    container_name: billing-service
    ports:
      - "8008:8008"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKER_URL: ${KAFKA_BROKER_URL}
    depends_on:
      - db
    networks:
      - saas_network
    restart: unless-stopped

volumes:
  postgres_billing_data:

networks:
  saas_network:
    driver: bridge
    external: true